spring:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/nadula
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9191
  security:
    basic:
      enabled: false
  ignored: /**

